services:
  dada_dental:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://172.17.0.1:20171
        - https_proxy=http://172.17.0.1:20171
    environment:
      - http_proxy=http://172.17.0.1:20171
      - https_proxy=http://172.17.0.1:20171
    image: dada_dental_image
    container_name: dada_dental_container
    ports:
      - "8000:8000"
    volumes:
      - ~/code/python/github.com/yshujie/dada_dental:/opt/dada_dental
    working_dir: /opt/dada_dental
    network_mode: "bridge"