services:
  dada_dental:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
    image: dada_dental_image
    container_name: dada_dental_container
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ~/code/python/github.com/yshujie/dada_dental:/opt/dada_dental
    working_dir: /opt/dada_dental
    network_mode: "bridge"