version: "3.7"

services:
  dada_dental:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://127.0.0.1:20171
        - HTTPS_PROXY=http://127.0.0.1:20171
    image: dada_dental_image
    container_name: dada_dental_container
    ports:
      - "8000:8000"
    volumes:
      - ~/code/python/github.com/yshujie/dada_dental:/opt/dada_dental
    working_dir: /opt/dada_dental
    environment:
      - HTTP_PROXY=http://127.0.0.1:20171
      - HTTPS_PROXY=http://127.0.0.1:20171
    network_mode: "host"
